version: '3.8'

services:
  b1cron:
    image: gutenye/b1cron
    build:
      platforms:
        - linux/arm64
        - linux/amd64
    ports:
      - "8080:8080"
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./data:/app/data
      - ./config.yaml:/app/config.yaml:ro
    restart: unless-stopped
